// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DoubleDateRange struct {
	SelectedPeriod       *DateRange `protobuf:"bytes,1,opt,name=selected_period,json=selectedPeriod,proto3" json:"selected_period,omitempty"`
	PreviousPeriod       *DateRange `protobuf:"bytes,2,opt,name=previous_period,json=previousPeriod,proto3" json:"previous_period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DoubleDateRange) Reset()         { *m = DoubleDateRange{} }
func (m *DoubleDateRange) String() string { return proto.CompactTextString(m) }
func (*DoubleDateRange) ProtoMessage()    {}
func (*DoubleDateRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *DoubleDateRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleDateRange.Unmarshal(m, b)
}
func (m *DoubleDateRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleDateRange.Marshal(b, m, deterministic)
}
func (m *DoubleDateRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleDateRange.Merge(m, src)
}
func (m *DoubleDateRange) XXX_Size() int {
	return xxx_messageInfo_DoubleDateRange.Size(m)
}
func (m *DoubleDateRange) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleDateRange.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleDateRange proto.InternalMessageInfo

func (m *DoubleDateRange) GetSelectedPeriod() *DateRange {
	if m != nil {
		return m.SelectedPeriod
	}
	return nil
}

func (m *DoubleDateRange) GetPreviousPeriod() *DateRange {
	if m != nil {
		return m.PreviousPeriod
	}
	return nil
}

type DateRange struct {
	PeriodFrom           *Period  `protobuf:"bytes,1,opt,name=period_from,json=periodFrom,proto3" json:"period_from,omitempty"`
	PeriodTo             *Period  `protobuf:"bytes,2,opt,name=period_to,json=periodTo,proto3" json:"period_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateRange) Reset()         { *m = DateRange{} }
func (m *DateRange) String() string { return proto.CompactTextString(m) }
func (*DateRange) ProtoMessage()    {}
func (*DateRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *DateRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateRange.Unmarshal(m, b)
}
func (m *DateRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateRange.Marshal(b, m, deterministic)
}
func (m *DateRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateRange.Merge(m, src)
}
func (m *DateRange) XXX_Size() int {
	return xxx_messageInfo_DateRange.Size(m)
}
func (m *DateRange) XXX_DiscardUnknown() {
	xxx_messageInfo_DateRange.DiscardUnknown(m)
}

var xxx_messageInfo_DateRange proto.InternalMessageInfo

func (m *DateRange) GetPeriodFrom() *Period {
	if m != nil {
		return m.PeriodFrom
	}
	return nil
}

func (m *DateRange) GetPeriodTo() *Period {
	if m != nil {
		return m.PeriodTo
	}
	return nil
}

type Period struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Period) Reset()         { *m = Period{} }
func (m *Period) String() string { return proto.CompactTextString(m) }
func (*Period) ProtoMessage()    {}
func (*Period) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Period) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Period.Unmarshal(m, b)
}
func (m *Period) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Period.Marshal(b, m, deterministic)
}
func (m *Period) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Period.Merge(m, src)
}
func (m *Period) XXX_Size() int {
	return xxx_messageInfo_Period.Size(m)
}
func (m *Period) XXX_DiscardUnknown() {
	xxx_messageInfo_Period.DiscardUnknown(m)
}

var xxx_messageInfo_Period proto.InternalMessageInfo

func (m *Period) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Period) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Period) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

//Aggreated category response
type Categories struct {
	Result               []*CategoryResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Date                 *Period           `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Categories) Reset()         { *m = Categories{} }
func (m *Categories) String() string { return proto.CompactTextString(m) }
func (*Categories) ProtoMessage()    {}
func (*Categories) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *Categories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Categories.Unmarshal(m, b)
}
func (m *Categories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Categories.Marshal(b, m, deterministic)
}
func (m *Categories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Categories.Merge(m, src)
}
func (m *Categories) XXX_Size() int {
	return xxx_messageInfo_Categories.Size(m)
}
func (m *Categories) XXX_DiscardUnknown() {
	xxx_messageInfo_Categories.DiscardUnknown(m)
}

var xxx_messageInfo_Categories proto.InternalMessageInfo

func (m *Categories) GetResult() []*CategoryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Categories) GetDate() *Period {
	if m != nil {
		return m.Date
	}
	return nil
}

type CategoryResult struct {
	CategoryName         string   `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Ratings              int32    `protobuf:"varint,2,opt,name=ratings,proto3" json:"ratings,omitempty"`
	Score                int32    `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryResult) Reset()         { *m = CategoryResult{} }
func (m *CategoryResult) String() string { return proto.CompactTextString(m) }
func (*CategoryResult) ProtoMessage()    {}
func (*CategoryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *CategoryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryResult.Unmarshal(m, b)
}
func (m *CategoryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryResult.Marshal(b, m, deterministic)
}
func (m *CategoryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryResult.Merge(m, src)
}
func (m *CategoryResult) XXX_Size() int {
	return xxx_messageInfo_CategoryResult.Size(m)
}
func (m *CategoryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryResult.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryResult proto.InternalMessageInfo

func (m *CategoryResult) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *CategoryResult) GetRatings() int32 {
	if m != nil {
		return m.Ratings
	}
	return 0
}

func (m *CategoryResult) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

//Scores by ticket response
//Returns an array of tickets which include ticket ID and categories
type TicketScores struct {
	Id                   int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               []*CategoryResult `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TicketScores) Reset()         { *m = TicketScores{} }
func (m *TicketScores) String() string { return proto.CompactTextString(m) }
func (*TicketScores) ProtoMessage()    {}
func (*TicketScores) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *TicketScores) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketScores.Unmarshal(m, b)
}
func (m *TicketScores) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketScores.Marshal(b, m, deterministic)
}
func (m *TicketScores) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketScores.Merge(m, src)
}
func (m *TicketScores) XXX_Size() int {
	return xxx_messageInfo_TicketScores.Size(m)
}
func (m *TicketScores) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketScores.DiscardUnknown(m)
}

var xxx_messageInfo_TicketScores proto.InternalMessageInfo

func (m *TicketScores) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TicketScores) GetResult() []*CategoryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

//Overal quality score response
type Quality struct {
	Precentage           int32    `protobuf:"varint,1,opt,name=precentage,proto3" json:"precentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quality) Reset()         { *m = Quality{} }
func (m *Quality) String() string { return proto.CompactTextString(m) }
func (*Quality) ProtoMessage()    {}
func (*Quality) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *Quality) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quality.Unmarshal(m, b)
}
func (m *Quality) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quality.Marshal(b, m, deterministic)
}
func (m *Quality) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quality.Merge(m, src)
}
func (m *Quality) XXX_Size() int {
	return xxx_messageInfo_Quality.Size(m)
}
func (m *Quality) XXX_DiscardUnknown() {
	xxx_messageInfo_Quality.DiscardUnknown(m)
}

var xxx_messageInfo_Quality proto.InternalMessageInfo

func (m *Quality) GetPrecentage() int32 {
	if m != nil {
		return m.Precentage
	}
	return 0
}

//Period over period response
type PeriodChange struct {
	Selected             *Period  `protobuf:"bytes,1,opt,name=selected,proto3" json:"selected,omitempty"`
	Previous             *Period  `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"`
	Change               int32    `protobuf:"varint,3,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeriodChange) Reset()         { *m = PeriodChange{} }
func (m *PeriodChange) String() string { return proto.CompactTextString(m) }
func (*PeriodChange) ProtoMessage()    {}
func (*PeriodChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *PeriodChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeriodChange.Unmarshal(m, b)
}
func (m *PeriodChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeriodChange.Marshal(b, m, deterministic)
}
func (m *PeriodChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeriodChange.Merge(m, src)
}
func (m *PeriodChange) XXX_Size() int {
	return xxx_messageInfo_PeriodChange.Size(m)
}
func (m *PeriodChange) XXX_DiscardUnknown() {
	xxx_messageInfo_PeriodChange.DiscardUnknown(m)
}

var xxx_messageInfo_PeriodChange proto.InternalMessageInfo

func (m *PeriodChange) GetSelected() *Period {
	if m != nil {
		return m.Selected
	}
	return nil
}

func (m *PeriodChange) GetPrevious() *Period {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *PeriodChange) GetChange() int32 {
	if m != nil {
		return m.Change
	}
	return 0
}

func init() {
	proto.RegisterType((*DoubleDateRange)(nil), "service.DoubleDateRange")
	proto.RegisterType((*DateRange)(nil), "service.DateRange")
	proto.RegisterType((*Period)(nil), "service.Period")
	proto.RegisterType((*Categories)(nil), "service.Categories")
	proto.RegisterType((*CategoryResult)(nil), "service.CategoryResult")
	proto.RegisterType((*TicketScores)(nil), "service.TicketScores")
	proto.RegisterType((*Quality)(nil), "service.Quality")
	proto.RegisterType((*PeriodChange)(nil), "service.PeriodChange")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xdd, 0x7c, 0x34, 0x93, 0x4f, 0x4d, 0x29, 0x58, 0x1c, 0x50, 0xe5, 0x5e, 0x8a, 0x40,
	0xa5, 0x0a, 0x17, 0x24, 0x4e, 0x6d, 0xa3, 0xe6, 0x46, 0xc1, 0xf4, 0x1e, 0x6d, 0xec, 0xc1, 0x5d,
	0xd5, 0xf6, 0x46, 0xeb, 0x4d, 0x24, 0xdf, 0xb8, 0xf3, 0x07, 0xf8, 0xb9, 0xc8, 0xfb, 0xe1, 0x26,
	0x90, 0x48, 0xdc, 0x3c, 0xb3, 0xef, 0xbd, 0x99, 0x37, 0x33, 0x09, 0x0c, 0x4b, 0x92, 0x1b, 0x1e,
	0xd3, 0xe5, 0x4a, 0x0a, 0x25, 0xb0, 0x6b, 0xc3, 0xf0, 0x97, 0x07, 0xe3, 0x99, 0x58, 0x2f, 0x33,
	0x9a, 0x31, 0x45, 0x11, 0x2b, 0x52, 0xc2, 0xcf, 0x30, 0x2e, 0x29, 0xa3, 0x58, 0x51, 0xb2, 0x58,
	0x91, 0xe4, 0x22, 0x09, 0xbc, 0x33, 0xef, 0xa2, 0x3f, 0xc5, 0x4b, 0xa7, 0xd2, 0x80, 0xa3, 0x91,
	0x83, 0x7e, 0xd5, 0xc8, 0x9a, 0xbc, 0x92, 0xb4, 0xe1, 0x62, 0x5d, 0x3a, 0xb2, 0x7f, 0x98, 0xec,
	0xa0, 0x86, 0x1c, 0x3e, 0x41, 0xef, 0xb9, 0x8d, 0x2b, 0xe8, 0x1b, 0x81, 0xc5, 0x0f, 0x29, 0x72,
	0xdb, 0xc2, 0xb8, 0x51, 0x31, 0x94, 0x08, 0x0c, 0xe6, 0x4e, 0x8a, 0x1c, 0xdf, 0x43, 0xcf, 0x32,
	0x94, 0xb0, 0x55, 0xff, 0xc1, 0x1f, 0x1b, 0xc4, 0x83, 0x08, 0x67, 0xd0, 0xb1, 0x3d, 0x23, 0xb4,
	0x2a, 0x62, 0x52, 0x97, 0x68, 0x47, 0xfa, 0x1b, 0x5f, 0x40, 0x3b, 0x17, 0x85, 0x7a, 0xd4, 0x3a,
	0xed, 0xc8, 0x04, 0x38, 0x81, 0xa3, 0x84, 0x55, 0xc1, 0x91, 0xce, 0xd5, 0x9f, 0xe1, 0x12, 0xe0,
	0x96, 0x29, 0x4a, 0x85, 0xe4, 0x54, 0xe2, 0x07, 0xe8, 0x48, 0x2a, 0xd7, 0x99, 0x0a, 0xbc, 0xb3,
	0xa3, 0x8b, 0xfe, 0xf4, 0x55, 0x53, 0xde, 0x82, 0xaa, 0x48, 0x3f, 0x47, 0x16, 0x86, 0xe7, 0xd0,
	0x4a, 0x98, 0x22, 0xad, 0xb8, 0xa7, 0x5b, 0xfd, 0x18, 0x12, 0x8c, 0x76, 0xe9, 0x78, 0x0e, 0xc3,
	0xd8, 0x66, 0x16, 0x05, 0xcb, 0x49, 0xb7, 0xde, 0x8b, 0x06, 0x2e, 0xf9, 0x85, 0xe5, 0x84, 0x01,
	0x74, 0x25, 0x53, 0xbc, 0x48, 0x4b, 0x6b, 0xc2, 0x85, 0xb5, 0xb9, 0x32, 0x16, 0x92, 0x82, 0x96,
	0x31, 0xa7, 0x83, 0xf0, 0x1e, 0x06, 0x0f, 0x3c, 0x7e, 0x22, 0xf5, 0xbd, 0x0e, 0x4b, 0x1c, 0x81,
	0xcf, 0x13, 0x3b, 0x14, 0x9f, 0x27, 0x5b, 0xe6, 0xfc, 0xff, 0x32, 0x17, 0xbe, 0x85, 0xee, 0xb7,
	0x35, 0xcb, 0xb8, 0xaa, 0xf0, 0x0d, 0xc0, 0x4a, 0x52, 0x4c, 0x85, 0x62, 0x29, 0x59, 0xcd, 0xad,
	0x4c, 0xf8, 0xd3, 0x83, 0x81, 0xf1, 0x7c, 0xfb, 0xa8, 0xb7, 0xff, 0x0e, 0x8e, 0xdd, 0x65, 0x1d,
	0x5a, 0x7d, 0x03, 0xa8, 0xc1, 0xee, 0x92, 0x0e, 0xef, 0xdd, 0x02, 0xf0, 0x25, 0x74, 0x62, 0x5d,
	0xc3, 0xae, 0xd1, 0x46, 0xd3, 0xdf, 0x3e, 0x0c, 0xad, 0x7f, 0x43, 0xc5, 0x6b, 0xc0, 0xb9, 0x9b,
	0xc6, 0x4d, 0x65, 0xde, 0x4a, 0xdc, 0x73, 0xc8, 0xaf, 0x4f, 0x9b, 0xdc, 0xf6, 0x04, 0xaf, 0x3c,
	0xbc, 0x81, 0xd3, 0x39, 0xa9, 0xeb, 0x34, 0x95, 0x94, 0x32, 0x45, 0x89, 0x9b, 0xd4, 0x5e, 0x95,
	0x93, 0xbf, 0x07, 0xca, 0xb5, 0xc6, 0x1d, 0x9c, 0xcc, 0x49, 0x19, 0x1f, 0xf7, 0x1b, 0x92, 0xf6,
	0x6a, 0x83, 0x67, 0x85, 0xdd, 0x1f, 0xf0, 0x56, 0x37, 0x3b, 0x23, 0xfd, 0x04, 0x93, 0x39, 0xa9,
	0x5a, 0x81, 0x65, 0x6e, 0x2f, 0xfb, 0xda, 0x98, 0x34, 0x39, 0x8b, 0x5a, 0x76, 0xf4, 0xbf, 0xc6,
	0xc7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x91, 0xef, 0x4f, 0x46, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TicketServiceClient is the client API for TicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TicketServiceClient interface {
	GetScoresByTickets(ctx context.Context, in *DateRange, opts ...grpc.CallOption) (TicketService_GetScoresByTicketsClient, error)
	GetAggregatedCategory(ctx context.Context, in *DateRange, opts ...grpc.CallOption) (TicketService_GetAggregatedCategoryClient, error)
	GetPeriodOverPeriod(ctx context.Context, in *DoubleDateRange, opts ...grpc.CallOption) (*PeriodChange, error)
	GetOveralQuality(ctx context.Context, in *DateRange, opts ...grpc.CallOption) (*Quality, error)
}

type ticketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketServiceClient(cc grpc.ClientConnInterface) TicketServiceClient {
	return &ticketServiceClient{cc}
}

func (c *ticketServiceClient) GetScoresByTickets(ctx context.Context, in *DateRange, opts ...grpc.CallOption) (TicketService_GetScoresByTicketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TicketService_serviceDesc.Streams[0], "/service.TicketService/GetScoresByTickets", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticketServiceGetScoresByTicketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TicketService_GetScoresByTicketsClient interface {
	Recv() (*TicketScores, error)
	grpc.ClientStream
}

type ticketServiceGetScoresByTicketsClient struct {
	grpc.ClientStream
}

func (x *ticketServiceGetScoresByTicketsClient) Recv() (*TicketScores, error) {
	m := new(TicketScores)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ticketServiceClient) GetAggregatedCategory(ctx context.Context, in *DateRange, opts ...grpc.CallOption) (TicketService_GetAggregatedCategoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TicketService_serviceDesc.Streams[1], "/service.TicketService/GetAggregatedCategory", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticketServiceGetAggregatedCategoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TicketService_GetAggregatedCategoryClient interface {
	Recv() (*Categories, error)
	grpc.ClientStream
}

type ticketServiceGetAggregatedCategoryClient struct {
	grpc.ClientStream
}

func (x *ticketServiceGetAggregatedCategoryClient) Recv() (*Categories, error) {
	m := new(Categories)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ticketServiceClient) GetPeriodOverPeriod(ctx context.Context, in *DoubleDateRange, opts ...grpc.CallOption) (*PeriodChange, error) {
	out := new(PeriodChange)
	err := c.cc.Invoke(ctx, "/service.TicketService/GetPeriodOverPeriod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetOveralQuality(ctx context.Context, in *DateRange, opts ...grpc.CallOption) (*Quality, error) {
	out := new(Quality)
	err := c.cc.Invoke(ctx, "/service.TicketService/GetOveralQuality", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServiceServer is the server API for TicketService service.
type TicketServiceServer interface {
	GetScoresByTickets(*DateRange, TicketService_GetScoresByTicketsServer) error
	GetAggregatedCategory(*DateRange, TicketService_GetAggregatedCategoryServer) error
	GetPeriodOverPeriod(context.Context, *DoubleDateRange) (*PeriodChange, error)
	GetOveralQuality(context.Context, *DateRange) (*Quality, error)
}

// UnimplementedTicketServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTicketServiceServer struct {
}

func (*UnimplementedTicketServiceServer) GetScoresByTickets(req *DateRange, srv TicketService_GetScoresByTicketsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetScoresByTickets not implemented")
}
func (*UnimplementedTicketServiceServer) GetAggregatedCategory(req *DateRange, srv TicketService_GetAggregatedCategoryServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAggregatedCategory not implemented")
}
func (*UnimplementedTicketServiceServer) GetPeriodOverPeriod(ctx context.Context, req *DoubleDateRange) (*PeriodChange, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeriodOverPeriod not implemented")
}
func (*UnimplementedTicketServiceServer) GetOveralQuality(ctx context.Context, req *DateRange) (*Quality, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOveralQuality not implemented")
}

func RegisterTicketServiceServer(s *grpc.Server, srv TicketServiceServer) {
	s.RegisterService(&_TicketService_serviceDesc, srv)
}

func _TicketService_GetScoresByTickets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DateRange)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TicketServiceServer).GetScoresByTickets(m, &ticketServiceGetScoresByTicketsServer{stream})
}

type TicketService_GetScoresByTicketsServer interface {
	Send(*TicketScores) error
	grpc.ServerStream
}

type ticketServiceGetScoresByTicketsServer struct {
	grpc.ServerStream
}

func (x *ticketServiceGetScoresByTicketsServer) Send(m *TicketScores) error {
	return x.ServerStream.SendMsg(m)
}

func _TicketService_GetAggregatedCategory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DateRange)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TicketServiceServer).GetAggregatedCategory(m, &ticketServiceGetAggregatedCategoryServer{stream})
}

type TicketService_GetAggregatedCategoryServer interface {
	Send(*Categories) error
	grpc.ServerStream
}

type ticketServiceGetAggregatedCategoryServer struct {
	grpc.ServerStream
}

func (x *ticketServiceGetAggregatedCategoryServer) Send(m *Categories) error {
	return x.ServerStream.SendMsg(m)
}

func _TicketService_GetPeriodOverPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoubleDateRange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetPeriodOverPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.TicketService/GetPeriodOverPeriod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetPeriodOverPeriod(ctx, req.(*DoubleDateRange))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetOveralQuality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateRange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetOveralQuality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.TicketService/GetOveralQuality",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetOveralQuality(ctx, req.(*DateRange))
	}
	return interceptor(ctx, in, info, handler)
}

var _TicketService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.TicketService",
	HandlerType: (*TicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeriodOverPeriod",
			Handler:    _TicketService_GetPeriodOverPeriod_Handler,
		},
		{
			MethodName: "GetOveralQuality",
			Handler:    _TicketService_GetOveralQuality_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetScoresByTickets",
			Handler:       _TicketService_GetScoresByTickets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAggregatedCategory",
			Handler:       _TicketService_GetAggregatedCategory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
